// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRoRcfkkdXkreJAoFPQY_FZYlllO83Ybo',
    appId: '1:965918215895:web:042707b560e4782c0fea92',
    messagingSenderId: '965918215895',
    projectId: 'temesgen-2a9fe',
    authDomain: 'temesgen-2a9fe.firebaseapp.com',
    storageBucket: 'temesgen-2a9fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjWoGibsOvlxFA7QqmbqZJA1nLEiqO7vk',
    appId: '1:965918215895:android:97146c775f720c7d0fea92',
    messagingSenderId: '965918215895',
    projectId: 'temesgen-2a9fe',
    storageBucket: 'temesgen-2a9fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlaR_0RMp5V3rVVo2tTsw0xyS-WYc_riY',
    appId: '1:965918215895:ios:c78b2a6b25458eed0fea92',
    messagingSenderId: '965918215895',
    projectId: 'temesgen-2a9fe',
    storageBucket: 'temesgen-2a9fe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlaR_0RMp5V3rVVo2tTsw0xyS-WYc_riY',
    appId: '1:965918215895:ios:c78b2a6b25458eed0fea92',
    messagingSenderId: '965918215895',
    projectId: 'temesgen-2a9fe',
    storageBucket: 'temesgen-2a9fe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRoRcfkkdXkreJAoFPQY_FZYlllO83Ybo',
    appId: '1:965918215895:web:75fb187c086cc5e20fea92',
    messagingSenderId: '965918215895',
    projectId: 'temesgen-2a9fe',
    authDomain: 'temesgen-2a9fe.firebaseapp.com',
    storageBucket: 'temesgen-2a9fe.firebasestorage.app',
  );
}
